services:
  agro-db:
    image: postgres:15
    container_name: agro-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agro_prototipo_db
    networks:
      - agro-network
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  agro-pgadmin:
    image: dpage/pgadmin4:latest
    container_name: agro-pgadmin
    depends_on:
      - agro-db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - agro-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  agro-network:
    driver: bridge

volumes:
  pgdata:
  pgadmin-data:
