version: '3.8'

services:
  agro-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agro_prototipo_db
    networks:
      - agro-network
    ports:
      - "5432:5432"

  agro-pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - agro-db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    restart: always
    networks:
      - agro-network

networks:
  agro-network:
    driver: bridge
