spring:
  application:
    name: prototipo-back-agro-spring

  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:agro_prototipo_db}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configuração do Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  # Desabilita os parâmetros automáticos do Pageable no Swagger UI
  show-actuator: false
  model-and-view-allowed: false

jwt:
  secret: ${JWT_SECRET:agromais-default-secret-key-change-in-production}
  expiration: ${JWT_EXPIRATION:86400000}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.agromaisprati: ${LOGGING_LEVEL_COM_AGROMAISPRATI:INFO}